from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QStandardItemModel, QStandardItem

from Task import *
from DBHandler import *
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(849, 712)
        MainWindow.setStyleSheet("background-color: rgb(255, 170, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 161, 711))
        self.frame.setStyleSheet("alternate-background-color: rgb(119, 249, 255);\n"
        "background-color: rgb(64, 131, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.addTaskMenu = QtWidgets.QPushButton(self.frame)
        self.addTaskMenu.setGeometry(QtCore.QRect(20, 40, 121, 51))
        self.addTaskMenu.clicked.connect(self.showAddTaskFrame)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.addTaskMenu.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/ramam/Desktop/PMP/TodoDesktop/icons/task.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addTaskMenu.setIcon(icon)
        self.addTaskMenu.setObjectName("addTaskMenu")
        self.searchTaskMenu = QtWidgets.QPushButton(self.frame)
        self.searchTaskMenu.setGeometry(QtCore.QRect(20, 540, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.searchTaskMenu.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:/Users/ramam/Desktop/PMP/TodoDesktop/icons/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.searchTaskMenu.setIcon(icon1)
        self.searchTaskMenu.setObjectName("searchTaskMenu")
        self.listTaskMenu = QtWidgets.QPushButton(self.frame)
        self.listTaskMenu.setGeometry(QtCore.QRect(20, 280, 121, 51))
        self.listTaskMenu.clicked.connect(self.showListTaskFrame)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.listTaskMenu.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:/Users/ramam/Desktop/PMP/TodoDesktop/icons/list.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.listTaskMenu.setIcon(icon2)
        self.listTaskMenu.setObjectName("listTaskMenu")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(190, 50, 591, 641))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.frame_2)
        self.calendarWidget.setGeometry(QtCore.QRect(230, 40, 312, 183))
        self.calendarWidget.setStyleSheet("background-color: rgb(93, 193, 255);")
        self.calendarWidget.setObjectName("calendarWidget")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(70, 50, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.addTaskTime = QtWidgets.QTimeEdit(self.frame_2)
        self.addTaskTime.setGeometry(QtCore.QRect(230, 240, 311, 22))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.addTaskTime.setFont(font)
        self.addTaskTime.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.addTaskTime.setObjectName("addTaskTime")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(80, 240, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(80, 310, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(80, 370, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.TaskNameEdit = QtWidgets.QLineEdit(self.frame_2)
        self.TaskNameEdit.setGeometry(QtCore.QRect(230, 310, 311, 31))
        self.TaskNameEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.TaskNameEdit.setObjectName("TaskNameEdit")
        self.TaskDescEdit = QtWidgets.QPlainTextEdit(self.frame_2)
        self.TaskDescEdit.setGeometry(QtCore.QRect(230, 380, 311, 151))
        self.TaskDescEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.TaskDescEdit.setObjectName("TaskDescEdit")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_5.setGeometry(QtCore.QRect(454, 552, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(170, 20, 641, 671))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(70, 40, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.todayTaskTable = QtWidgets.QTableView(self.frame_3)
        self.todayTaskTable.setGeometry(QtCore.QRect(180, 80, 431, 241))
        self.todayTaskTable.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.todayTaskTable.setDragDropOverwriteMode(False)
        self.todayTaskTable.setObjectName("todayTaskTable")
        self.todaysTaskTitle = QtWidgets.QLineEdit(self.frame_3)
        self.todaysTaskTitle.setGeometry(QtCore.QRect(180, 350, 431, 41))
        self.todaysTaskTitle.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.todaysTaskTitle.setObjectName("todaysTaskTitle")
        self.todaysTaskDesc = QtWidgets.QPlainTextEdit(self.frame_3)
        self.todaysTaskDesc.setGeometry(QtCore.QRect(180, 420, 431, 151))
        self.todaysTaskDesc.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.todaysTaskDesc.setObjectName("todaysTaskDesc")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_4.setGeometry(QtCore.QRect(324, 600, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.frame_3.raise_()
        self.frame.raise_()
        self.frame_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.addTaskMenu.setText(_translate("MainWindow", "Add Task"))
        self.searchTaskMenu.setText(_translate("MainWindow", "search"))
        self.listTaskMenu.setText(_translate("MainWindow", "List Task"))
        self.label.setText(_translate("MainWindow", " Select Date"))
        self.label_2.setText(_translate("MainWindow", "Select Time"))
        self.label_3.setText(_translate("MainWindow", "Task Title"))
        self.label_4.setText(_translate("MainWindow", "Description"))
        self.pushButton_5.setText(_translate("MainWindow", "Add Task"))

        self.label_5.setText(_translate("MainWindow", "Todays Tasks"))
        self.pushButton_4.setText(_translate("MainWindow", "View Task"))

        self.pushButton_5.clicked.connect(self.addTaskBtnClicked)
    def showAddTaskFrame(self):
        self.frame_2.show()
        self.frame_3.hide()
    def showListTaskFrame(self):
            self.frame_2.hide()
            self.frame_3.show()
            date = self.calendarWidget.selectedDate().toString()
            db = DBHandler()
            rows = db.getTasks(date)

            self.todayTaskTable.setSelectionBehavior(1)
            model = QStandardItemModel()
            model.setHorizontalHeaderLabels(["ID","Title","Description","Date","Time"])
            try:
                i = 0
                for row in rows:
                   for column in range(0,5):
                      item = QStandardItem(row[column])
                      model.setItem(i,column,item)
                   i+=1

                self.todayTaskTable.setModel(model)
            except Exception as e:
                print(e)
    def addTaskBtnClicked(self):
        taskDate = self.calendarAddTask.selectedDate().toString()
        taskTime = self.addTaskTime.time().toString()
        taskTitle = self.TaskNameEdit.text()
        taskDesc = self.TaskDescEdit.toPlainText()
        t = Task(taskTitle, taskDesc, taskDate, taskTime)
        db = DBHandler()
        db.insertTask(t)

    def showDetails(self):
        idx=self.todayTaskTable.selectedIndexes()
        id = idx[0]
        title = idx[1]
        desc = idx[2]
        #print(title.data())
        #taskid = index.data()
        try:
           self.todaysTaskTitle.setText(title.data())
           self.todaysTaskDesc.setPlainText(desc)
        except Exception as e:
            print(e)

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
